---
title: "Arriola_PCA"
author: "Arriola, Phoebe"
date: "2026-06-17"
output: html_document
---

```{r setup-and-data}
## A. Principal Component Analysis 
# 1. Read in the frogs’ data as a dataframe.
getwd()
setwd("/Users/phoebearriola/Desktop/uni")
list.files()
frogs_df <- read.csv("Meneses_et.al_2026_Platymantis.csv")

# 2. Subset your data to retain only the “Species” column and morphological features (e.g., SVL, HL, SNL, etc.) from columns 10 through the last one (i.e., 10:X).
frogs_subset <- frogs_df[, c(1, 10:ncol(frogs_df))]

# 3. Check the class and structure of the subset data. How many morphological features are present in the dataset?
class(frogs_subset)
str(frogs_subset)
num_features <- ncol(frogs_subset) - 1
print(paste("Number of morphological features:", num_features))
## The value 1 is subtracted from the subset because the first column describes the species. In the end, there are a total of 25 counts of morphological features in the dataset 

# 4. Ensure the dataframe has no NAs.
morph_numeric <- frogs_subset[, -1]
good <- complete.cases(morph_numeric)
morph_numeric <- morph_numeric[good, ]
species_vector <- frogs_subset$Species[good]

# 5. Scale the data using only the numeric columns, then compute the pairwise correlations. Do not further subset the data.
frogs_scaled <- scale(morph_numeric)
cor_mat <- cor(frogs_scaled)
print("Pairwise Correlation Matrix (Rounded):")
print(round(cor_mat, 2))

# 6. Use the correlation matrix to calculate the eigenvectors and the proportion of variance (expressed in percentage). How many principal components were produced? What is the proportion of variance explained by components 1–4?
eig <- eigen(cor_mat)
prop_var_pct <- (eig$values / sum(eig$values)) * 100
eig_vec <- eig$vectors
scores <- frogs_scaled %*% eig_vec
head(scores)

# Q: How many principal components were produced?
num_pcs <- length(prop_var_pct)
print(paste("Number of principal components produced:", num_pcs))

# A: the total number of produced principal components is 25

# Q: What is the proportion of variance explained by components 1–4?
print("Proportion of variance explained by components 1 to 4 individually (%):")
print(round(prop_var_pct[1:4], 2))

cumulative_variance_1_4 <- sum(prop_var_pct[1:4])
print(paste("Total cumulative variance explained by components 1-4 (%):", round(cumulative_variance_1_4, 2)))

# A: the total cumulative variance explained by components 1-4, presented in percentage is 61.77% 

# 7. Now, create a 1x2 plot showing the screeplot and the PCA biplot. You can use either base R or ggplot2. You can be creative here by coloring the point shapes per species and adding a legend. Consider the high data-ink ratio you learned from the lecture.
pca_res <- prcomp(frogs_scaled)
par(mfrow = c(1, 2))

# Screeplot: 
barplot(prop_var_pct, 
        names.arg = paste0("PC", 1:length(prop_var_pct)), 
        col = "lightskyblue", 
        xlab = "Principal Components",
        ylab = "% Variance Explained", 
        main = "Scree Plot")

# Biplot 
species_factor <- as.factor(species_vector)

plot(pca_res$x[,1], pca_res$x[,2], 
     col = c("darkorange", "purple")[species_factor], 
     pch = c(16, 17)[species_factor],
     xlab = paste0("PC1 (", round(prop_var_pct[1], 1), "%)"),
     ylab = paste0("PC2 (", round(prop_var_pct[2], 1), "%)"),
     main = "PCA Biplot Space")
legend("topright", 
       legend = levels(species_factor), 
       col = c("darkorange", "purple"), 
       pch = c(16, 17), 
       bty = "n")

## B. Broken-stick vs PCAtest
# 1. Examine the variance explained by principal components using the Broken-stick method and the PCAtest package. What is the difference between these two methods for assessing the importance of principal components?
broken_stick <- function(p){
  sapply(1:p, function(k){
    sum(1 / (k:p)) / p
  })
}
bs <- broken_stick(num_features)
bs

prop_var <- eig$values / sum(eig$values)

comparison <- data.frame(
  PC = paste0("PC", 1:num_features),
  Observed = prop_var,
  BrokenStick = bs
)
comparison

par(mfrow = c(1, 1))

# 2. Create a barplot showing the results of Broken-stick analysis and perform a significance test for principal components using PCAtest, following the instructions at https://arleyc.github.io/PCAtest/.
plot(prop_var,
     type = "b",
     pch = 19,
     ylim = c(0, max(prop_var)),
     xlab = "Principal Component",
     ylab = "Proportion of Variance",
     main = "Broken-Stick Analysis")
lines(bs,
      type = "b",
      pch = 17,
      col = "red")
legend("topright",
       legend = c("Observed", "Broken Stick"),
       pch = c(19, 17),
       col = c("black", "red"))

library(PCAtest)
frog_pca_test <- PCAtest(frogs_scaled, 100, 100, 0.05, varcorr=FALSE, counter=FALSE, plot=TRUE)

### Interpretation of Part B: Broken-stick vs PCAtest

# The broken-stick and PCAtest methods help in assessing principal components and which ones have significant biological data instead of random noise 

# Broken-stick - compares the eigenvalue of each PCA component to random values. If the eigenvalue is larger than the corresponding number of broken-stick, then it is considered as significant.

# PCA test - utilizes permutations as the data is randomized or shuffled multiple times. If a component presents a variance that is significantly greater than what is expected from random data, then that component is said to be significant.  
